const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal');let state,project,records=[],activity=[],members=[],page='Overview',authMode='',timer=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const toast=s=>{$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4500)};
async function api(route,data){const r=await fetch('/api/'+route,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const b=await r.json();if(!r.ok)throw new Error(b.error);return b}
const brand=()=>'<div class="brand"><img src="/logo.svg" alt="Apex logo"><div>apex<span style="color:var(--brand)">.</span><small>Workspace</small></div></div>';
const field=(name,label,type='text',value='')=>`<label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${type==='password'?'minlength="12" maxlength="128" autocomplete="new-password"':''} required>`;
const select=(name,label,options)=>`<label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${options}</select>`;
const opts=(xs,key='name')=>xs.map(x=>`<option value="${x.id}">${esc(x[key])}</option>`).join('');
const check=(n,t)=>`<label><input type="checkbox" name="${n}">${t}</label>`;
const empty=(title,text)=>`<div class="empty"><strong>${title}</strong>${text}</div>`;
const button=(action,text,cls='')=>`<button class="${cls}" data-action="${action}">${text}</button>`;
const kinds=k=>records.filter(r=>r.kind===k);
function showForm(title,html,submit){modal.innerHTML=`<h2>${title}</h2><form>${html}<div class="error" role="alert"></div><div class="actions"><button type="button" data-action="close">Cancel</button><button class="primary">Save changes</button></div></form>`;modal.showModal();modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=Object.fromEntries(new FormData(f));f.querySelectorAll('[type=checkbox]').forEach(x=>b[x.name]=x.checked);try{await submit(b,f);modal.close();await load();toast('Saved successfully')}catch(e){f.querySelector('.error').textContent=e.message}}}
async function auth(mode){authMode=mode;const setup=mode==='setup',forgot=mode==='forgot',reset=mode==='reset';app.innerHTML=`<div class="auth"><section class="authstory">${brand()}<div><div class="eyebrow">A little less chaos. A lot more clarity.</div><h1>Great work.<br>Better together.</h1><p>Your team, your clients, and every big idea. Finally in one workspace.</p><div class="art"><div class="row"><b>Brand launch campaign</b><span class="pill green">On track</span></div><p style="font-size:12px;margin-top:10px">From first brief to final approval.</p><div class="bar"><span></span></div><div class="row"><span class="avatar">A</span><small>Built for your next big thing ↗</small></div></div></div><small>APEX WORKSPACE · MADE FOR CREATIVE TEAMS</small></section><div class="authform"><section>${brand()}<h2>${setup?'Make it your workspace.':forgot?'Forgot your password?':reset?'A fresh start.':'Welcome back.'}</h2><p class="muted">${setup?'Create the first super admin account to get started.':forgot?'We’ll send a secure reset link to your email.':reset?'Choose a new password with at least 12 characters.':'Sign in to keep great work moving.'}</p><form id="authForm">${setup?field('name','Your full name'):''}${!reset?field('email','Email address','email'):''}${!forgot?field('password',setup||reset?'Create password · 12+ characters':'Password','password'):''}<div class="error" role="alert"></div><button class="primary">${setup?'Create workspace →':forgot?'Send reset link →':reset?'Reset password →':'Sign in →'}</button></form><div style="text-align:center;margin-top:20px">${button(forgot||reset?'login':'forgot',forgot||reset?'Back to sign in':'Forgot password?','quiet')}</div><p class="muted" style="font-size:11px;text-align:center;margin-top:35px">Your account permissions are assigned by your agency.<br>Need access? Contact your workspace administrator.</p></section></div></div>`;
$('#authForm').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));try{if(reset)b.token=new URLSearchParams(location.search).get('reset');const r=await api(mode,b);if(forgot){toast(r.message);return}if(setup){await api('login',{email:b.email,password:b.password})}if(reset){history.replaceState({},'','/');await auth('login');toast('Password updated. Please sign in.');return}await load()}catch(err){$('.error').textContent=err.message}}}
async function load(){try{state=await api('state');project=state.projects.find(p=>p.id===Number(project?.id))||state.projects[0];if(project){const r=await api('records?project='+project.id);records=r.records;activity=r.audit;members=r.members}else{records=[];activity=[];members=[]}render()}catch(e){if(e.message==='Please sign in')auth('login');else toast(e.message)}}
const modules=[['Organizations','Multi-tenant organization & branding','Create isolated organizations, set colors and upload a logo. Subdomain names are stored; DNS routing is a deployment step.'],['Team & access','Role-based access control','Super admin, project manager, staff and client roles. Add explicit project assignments here.'],['Task board','Kanban tasks & milestones','Drag cards between four stages or use the accessible status menu. Mark milestone tasks when creating them.'],['Document vault','Document vault & sign-off','Upload images or PDFs, retain versions, and record who approved each version and when.'],['Feedback','Visual feedback & revisions','Place comments on image coordinates. Each comment also creates a revision task. PDF feedback is not supported yet.'],['Discussions','Project discussion hub','Project messages, optional private staff threads, and automatic refresh every five seconds.'],['Time tracking','Time & unbilled hours','Start a timer or add hours manually. Choose a billable rate per entry.'],['Invoices','Invoices & payments','Convert unbilled hours to an invoice, print to PDF, and pay through Stripe when connected.']];
const nav=[['Overview','◫'],['Task board','▦'],['Document vault','▧'],['Feedback','◎'],['Discussions','☷'],['Time tracking','◷'],['Invoices','▤'],['Organizations','◇'],['Team & access','♧'],['Visitor activity','↗'],['Setup guide','?']];
function render(){const org=state.orgs.find(o=>o.id===project?.org);document.documentElement.style.setProperty('--brand',org?.color||'#7662ea');const visible=nav.filter(([n])=>state.user.role==='admin'||!['Organizations','Team & access','Visitor activity'].includes(n)).filter(([n])=>state.user.role!=='client'||n!=='Time tracking');if(!visible.some(([n])=>n===page))page='Overview';app.innerHTML=`<aside class="sidebar">${org?.logo?`<div class="brand"><img src="${esc(org.logo)}" alt="Organization logo"><div>${esc(org.name)}</div></div>`:brand()}<div class="navlabel">YOUR WORKSPACE</div><nav class="nav">${visible.map(([n,i])=>`<button data-page="${n}" class="${page===n?'active':''}"><i>${i}</i>${n}</button>`).join('')}</nav><div class="bottom"><div class="row"><span class="avatar">${esc(state.user.name.slice(0,2).toUpperCase())}</span><div><b>${esc(state.user.name)}</b><br><small>${esc(state.user.role==='admin'?'Super Admin':state.user.role)}</small></div></div>${button('logout','Sign out','quiet')}</div></aside><header class="topbar"><span class="muted">Workspace <span style="margin:0 10px">/</span> <b style="color:var(--ink)">${page}</b></span><div class="row"><select id="projectSelect" aria-label="Select project">${opts(state.projects)||'<option>No projects yet</option>'}</select><span class="avatar">${esc(state.user.name.slice(0,1))}</span></div></header><main><div class="row pagehead"><div><h1>${page==='Overview'?`Let’s make things happen, ${esc(state.user.name.split(' ')[0])}.`:page}</h1><p class="muted">${page==='Overview'?'Here’s what’s happening across your workspace.':esc(project?.name||'Your agency workspace')}</p></div>${headAction()}</div><div id="content">${content()}</div></main>`;if(project)$('#projectSelect').value=project.id;$('#projectSelect').onchange=e=>{project=state.projects.find(p=>p.id===+e.target.value);load()};wireBoard()}
function headAction(){if(page==='Organizations')return button('org','＋ New organization','primary');if(page==='Team & access')return button('user','＋ Add team member','primary');if(!project)return state.user.role==='admin'?button(state.orgs.length?'project':'org',state.orgs.length?'＋ New project':'＋ Create organization','primary'):'';return ({'Overview':state.user.role==='admin'?button('project','＋ New project','primary'):'','Task board':state.user.role!=='client'?button('task','＋ New task','primary'):'','Document vault':state.user.role!=='client'?button('upload','↑ Upload file','primary'):'','Time tracking':button('time','＋ Log time','primary'),'Invoices':['admin','manager'].includes(state.user.role)?button('invoice','＋ Generate invoice','primary'):''})[page]||''}
function content(){if(page==='Setup guide')return `<div class="panel"><h2>Your first eight modules</h2><p class="muted">This local version has a real SQLite database. Some requested advanced features still need implementation or service configuration.</p>${modules.map((m,i)=>`<div class="module"><span class="eyebrow">MODULE 0${i+1} · ${m[0]}</span><b>${m[1]}</b><span class="muted">${m[2]}</span></div>`).join('')}<div class="notice">Email: ${state.services.email?'configured; verify sender before use':'not connected'} · Payments: ${state.services.payments?'configured; test webhooks before launch':'not connected'}. Read README.md for setup and remaining production work.</div></div>`;
if(page==='Organizations')return `<div class="cards">${state.orgs.map(o=>`<div class="panel"><span class="avatar" style="background:${esc(o.color)};color:white">${esc(o.name[0])}</span><h2 style="margin-top:20px">${esc(o.name)}</h2><p class="muted">${state.projects.filter(p=>p.org===o.id).length} projects · Isolated workspace</p>${button('brand:'+o.id,'Edit branding')}${button('project:'+o.id,'Add project','quiet')}</div>`).join('')}</div>${!state.orgs.length?empty('Your first client starts here.','Create an organization, then add its projects and people.'):''}`;
if(page==='Team & access')return `<div class="panel"><div class="row"><h2>People & permissions</h2>${button('assign','Assign project access')}</div><div class="tablewrap"><table><tr><th>NAME</th><th>EMAIL</th><th>ROLE</th><th>ORGANIZATION</th><th></th></tr>${state.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td><span class="pill">${esc(u.role)}</span></td><td>${esc(state.orgs.find(o=>o.id===u.org)?.name||'Agency owner')}</td><td>${button('deleteuser:'+u.id,'Delete','quiet')}</td></tr>`).join('')}</table></div></div>`;
if(page==='Visitor activity')return `<div class="panel"><h2>Authenticated visits</h2><p class="muted">Records successful sign-ins, not anonymous visitors or employee screen activity. Up to 100 recent visits are shown.</p><table><tr><th>PERSON</th><th>EMAIL</th><th>SIGNED IN (UTC)</th></tr>${state.visits.map(v=>`<tr><td>${esc(v.name)}</td><td>${esc(v.email)}</td><td>${esc(v.created)}</td></tr>`).join('')}</table></div>`;
if(!project)return `<section class="hero"><div class="eyebrow">WELCOME TO YOUR NEXT CHAPTER</div><h2>A clear space for great work.</h2><p>Bring your clients, creatives, and campaigns together. Start with an organization and project.</p>${state.user.role==='admin'?button(state.orgs.length?'project':'org',state.orgs.length?'Create your first project →':'Set up your first client →','primary'):''}</section>${state.user.role==='admin'&&state.orgs.length?`<div class="panel"><h2>Your organizations</h2><p class="muted">Your organizations are saved. Add a project to start working with tasks, files and conversations.</p>${state.orgs.map(o=>`<div class="row listrow"><b>${esc(o.name)}</b>${button('project:'+o.id,'＋ Add project','primary')}</div>`).join('')}</div>`:empty('No projects assigned yet',state.user.role==='admin'?'Create an organization to get started.':'Ask your administrator to assign you to a project.')}`;
if(page==='Overview'){const tasks=kinds('task'),approved=tasks.filter(t=>t.data.status==='Approved').length;return `<section class="hero"><div class="eyebrow">BIG IDEAS. ONE SHARED SPACE.</div><h2>Your next great campaign starts here.</h2><p>${esc(project.description||'Keep every deliverable, conversation, and approval moving in the right direction.')}</p><button class="primary" data-page="Task board">Open task board ↗</button></section><div class="stats">${[['▦','Project tasks',tasks.length,'Across all stages'],['◎','Awaiting review',tasks.filter(t=>t.data.status==='Client Review').length,'Ready for a fresh pair of eyes'],['✓','Approved',approved,`${tasks.length?Math.round(approved/tasks.length*100):0}% of tasks completed`],['▤','Outstanding',money(kinds('invoice').filter(r=>r.data.status!=='Paid').reduce((s,r)=>s+r.data.amount/100,0)),'Unpaid invoices']].map(([i,t,n,s])=>`<div class="stat"><span class="icon">${i}</span><small>${t}</small><strong>${n}</strong><small>${s}</small></div>`).join('')}</div><div class="grid2"><div class="panel"><div class="row"><h2>Work in focus</h2><button class="quiet" data-page="Task board">View board →</button></div>${tasks.slice(0,5).map(t=>`<div class="row listrow"><div><b>${esc(t.data.title)}</b><p class="muted">${t.data.milestone?'Milestone':'Task'} · ${esc(t.data.due||'No due date')}</p></div><span class="pill ${t.data.status==='Approved'?'green':''}">${esc(t.data.status)}</span></div>`).join('')||empty('A clean slate.','Add your first task to start tracking progress.')}</div><div class="panel"><h2>${state.user.role==='client'?'Shared documents':'Recent activity'}</h2>${(state.user.role==='client'?kinds('document').map(d=>({action:d.data.title,name:d.author_name,created:d.created})):activity).slice(0,5).map(a=>`<div class="listrow"><b>${esc(a.action)}</b><p><small>${esc(a.name||'System')} · ${esc(a.created)} UTC</small></p></div>`).join('')||empty('Nothing to catch up on.','New activity will appear here.')}</div></div>`}
if(page==='Task board')return `<div class="board">${['Backlog','In Progress','Client Review','Approved'].map(status=>`<section class="column" data-status="${status}"><h3>${status} <span class="muted">${kinds('task').filter(t=>t.data.status===status).length}</span></h3>${kinds('task').filter(t=>t.data.status===status).map(t=>`<article class="task" draggable="${state.user.role!=='client'}" data-id="${t.id}"><span class="pill">${t.data.milestone?'Milestone':t.data.internal?'Internal':'Client shared'}</span><h3>${esc(t.data.title)}</h3><small>${esc(t.data.due||'No due date')}</small>${state.user.role!=='client'?`<select aria-label="Status for ${esc(t.data.title)}" data-task="${t.id}">${['Backlog','In Progress','Client Review','Approved'].map(s=>`<option ${status===s?'selected':''}>${s}</option>`).join('')}</select>`:status==='Client Review'?button('taskapprove:'+t.id,'Approve'):''}</article>`).join('')}</section>`).join('')}</div>`;
if(page==='Document vault'||page==='Feedback')return `<div class="cards">${kinds('document').map(d=>`<div class="panel"><div class="row"><span class="pill">${d.data.mime==='application/pdf'?'PDF':'IMAGE'} · v${d.data.version}</span><small>${d.data.internal?'Internal':'Client shared'}</small></div><h2 style="margin-top:20px">${esc(d.data.title)}</h2><p class="muted">${esc(d.author_name)} · ${esc(d.created.slice(0,10))}</p><p><span class="pill ${d.data.approval?'green':'orange'}">${d.data.approval?'Approved':'Awaiting approval'}</span></p><div class="row"><a href="/api/file/${d.id}" target="_blank" rel="noopener">Open file ↗</a>${d.data.mime.startsWith('image/')?button('feedback:'+d.id,'View & annotate'):''}</div>${!d.data.approval&&['admin','client'].includes(state.user.role)?button('approve:'+d.id,'Sign & approve','quiet'):''}${d.data.approval?`<small>Approved by ${esc(d.data.approval.name)}<br>${esc(d.data.approval.time)}</small>`:''}</div>`).join('')}</div>${!kinds('document').length?empty('Your work deserves a home.','Upload a draft image or PDF in Document vault to get started.'):''}`;
if(page==='Discussions')return `<div class="panel"><div class="row"><h2># ${esc(project.name)}</h2><small>Updates every 5 seconds</small></div><div class="chat" id="messages">${messages()}</div><form id="messageForm"><div class="compose"><textarea name="text" required maxlength="5000" aria-label="Message" placeholder="Keep the conversation moving…"></textarea><button class="primary">Send →</button></div>${state.user.role!=='client'?check('internal','Internal team only'):''}</form></div>`;
if(page==='Time tracking')return `<div class="panel" style="margin-bottom:20px"><div class="row"><div><h2>Make every hour count.</h2><span class="muted">${timer?'Timer running since '+new Date(timer.start).toLocaleTimeString():'Start a timer, or add your hours manually.'}</span></div>${button(timer?'stop':'start',timer?'■ Stop & log':'▶ Start timer','primary')}</div></div><div class="panel tablewrap"><table><tr><th>WORK</th><th>HOURS</th><th>RATE</th><th>VALUE</th><th>STATUS</th></tr>${kinds('time').map(t=>`<tr><td>${esc(t.data.title)}<br><small>${esc(t.author_name)}</small></td><td>${t.data.hours.toFixed(2)}</td><td>${money(t.data.rate)}/h</td><td>${money(t.data.hours*t.data.rate)}</td><td><span class="pill">${t.data.billed?'Invoiced':t.data.billable?'Unbilled':'Non-billable'}</span></td></tr>`).join('')}</table>${!kinds('time').length?empty('No hours logged yet.','Track your first work session above.'):''}</div>`;
if(page==='Invoices')return `<div class="panel tablewrap"><table><tr><th>INVOICE</th><th>AMOUNT</th><th>DUE</th><th>STATUS</th><th></th></tr>${kinds('invoice').map(r=>`<tr><td><b>INV-${String(r.id).padStart(4,'0')}</b><br><small>${esc(r.data.title)}</small></td><td>${money(r.data.amount/100)}</td><td>${esc(r.data.due||'On receipt')}</td><td><span class="pill ${r.data.status==='Paid'?'green':'orange'}">${r.data.status}</span></td><td>${button('viewinvoice:'+r.id,'View invoice')}${r.data.status!=='Paid'?button('pay:'+r.id,'Pay →','quiet'):''}</td></tr>`).join('')}</table>${!kinds('invoice').length?empty('Ready when the work is.','Log billable hours, then generate your first invoice.'):''}</div>`;
return ''}
function messages(){return kinds('message').reverse().map(m=>`<div class="message"><b>${esc(m.author_name)}</b> <small>${esc(m.created)} UTC ${m.data.internal?'· Internal':''}</small><p>${esc(m.data.text)}</p></div>`).join('')||empty('Good projects start with a conversation.','Share an update with your project team.')}
function wireBoard(){document.querySelectorAll('[data-task]').forEach(s=>s.onchange=async()=>{try{await api('task',{id:+s.dataset.task,status:s.value});await load()}catch(e){toast(e.message);load()}});document.querySelectorAll('[draggable=true]').forEach(c=>c.ondragstart=e=>e.dataTransfer.setData('text/plain',c.dataset.id));document.querySelectorAll('[data-status]').forEach(c=>{c.ondragover=e=>e.preventDefault();c.ondrop=async e=>{e.preventDefault();try{await api('task',{id:+e.dataTransfer.getData('text/plain'),status:c.dataset.status});load()}catch(e){toast(e.message)}}});if($('#messageForm'))$('#messageForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await api('records',{project:project.id,kind:'message',text:f.text.value,internal:f.internal?.checked||false});await load();$('#messages').scrollTop=999999}catch(e){toast(e.message)}}}
const readFile=f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)});
async function action(a){const [cmd,id]=a.split(':');if(cmd==='close'){modal.close();return}if(['login','forgot'].includes(cmd)){auth(cmd);return}if(cmd==='logout'){await api('logout',{});auth('login');return}if(cmd==='deleteuser'){if(!confirm('Delete this team member and remove their access?'))return;await api('users/delete',{id:Number(id)});await load();toast('Team member deleted');return}
if(cmd==='org'||cmd==='brand'){const o=state.orgs.find(o=>o.id===+id);showForm(o?'Workspace branding':'Create an organization',field('name','Organization name','text',o?.name||'')+field('color','Brand color','color',o?.color||'#7662ea')+'<label>Logo (PNG, JPEG or WebP, up to 500 KB)</label><input type="file" name="logoFile" accept="image/png,image/jpeg,image/webp"><label>Preferred subdomain (requires hosting setup)</label><input name="subdomain" value="'+esc(o?.subdomain||'')+'">',async(b,f)=>{const file=f.logoFile.files[0];if(file&&file.size>500000)throw Error('Logo must be under 500 KB');await api('orgs',{...b,id:o?.id,logo:file?await readFile(file):o?.logo||''});page='Organizations'});return}
if(cmd==='project'){if(!state.orgs.length)throw Error('Create an organization first');showForm('New client project',field('name','Project name')+select('org','Organization',opts(state.orgs))+'<label>Project brief</label><textarea name="description"></textarea>',b=>api('projects',b));if(id)modal.querySelector('[name=org]').value=id;return}
if(cmd==='user'){if(!state.orgs.length)throw Error('Create an organization first');showForm('Add a team member',field('name','Full name')+field('email','Email','email')+field('password','Initial password · 12+ characters','password')+select('role','Role','<option value="staff">Developer / Designer</option><option value="manager">Project Manager</option><option value="client">Client User</option>')+select('org','Organization',opts(state.orgs)),b=>api('users',b));return}
if(cmd==='assign'){if(!project)throw Error('Create a project first');showForm('Assign access to '+esc(project.name),select('user','Team member',opts(state.users.filter(u=>u.org===project.org))),b=>api('members',{...b,project:project.id}));return}
if(cmd==='task'){showForm('Create a task',field('title','Task title')+'<label>Due date</label><input name="due" type="date">'+check('milestone','This is a milestone')+check('internal','Internal team only'),b=>api('records',{...b,kind:'task',project:project.id}));return}
if(cmd==='taskapprove'){await api('task',{id:+id,status:'Approved'});await load();return}
if(cmd==='upload'){showForm('Upload a deliverable','<p class="muted">Use the same title to create the next version.</p>'+field('title','Document title')+'<label>File · maximum 5 MB</label><input name="asset" type="file" accept="image/png,image/jpeg,image/webp,application/pdf" required>'+check('internal','Internal team only'),async(b,f)=>{const file=f.asset.files[0];if(file.size>5000000)throw Error('Maximum file size is 5 MB');const data=await readFile(file);await api('records',{...b,kind:'document',project:project.id,mime:file.type,content:data.split(',')[1]})});return}
if(cmd==='approve'){const d=records.find(r=>r.id===+id);showForm('Approve this version',`<p>You are approving <b>${esc(d.data.title)} v${d.data.version}</b> as ${esc(state.user.name)}. Your name, email, and timestamp will be recorded.</p>${check('consent','I approve this version for delivery.')}`,async b=>{if(!b.consent)throw Error('Please confirm your approval');await api('approve',{id:+id})});return}
if(cmd==='feedback'){const d=records.find(r=>r.id===+id),pins=kinds('feedback').filter(r=>r.data.document===+id);modal.innerHTML=`<h2>${esc(d.data.title)} · v${d.data.version}</h2><p class="muted">Click the image to leave a revision pin.</p><div class="preview"><img src="/api/file/${id}" alt="${esc(d.data.title)}">${pins.map((p,i)=>`<span class="pin" style="left:${p.data.x*100}%;top:${p.data.y*100}%" title="${esc(p.data.text)}">${i+1}</span>`).join('')}</div><div id="pinForm"></div>${pins.map((p,i)=>`<p class="listrow"><b>${i+1}. ${esc(p.author_name)}</b><br>${esc(p.data.text)}</p>`).join('')}<div class="actions">${button('close','Close')}</div>`;modal.showModal();modal.querySelector('.preview img').onclick=e=>{const rect=e.target.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width,y=(e.clientY-rect.top)/rect.height;$('#pinForm').innerHTML='<form><label>Revision comment</label><textarea name="text" required maxlength="2000"></textarea><button class="primary">Save pin & create revision task</button></form>';$('#pinForm form').onsubmit=async e=>{e.preventDefault();try{await api('records',{kind:'feedback',project:project.id,document:+id,x,y,text:e.currentTarget.text.value});modal.close();await load();action(a)}catch(e){toast(e.message)}}};return}
if(cmd==='start'){timer={start:Date.now(),project:project.id};render();return}
if(cmd==='time'||cmd==='stop'){if(cmd==='stop'&&timer.project!==project.id)throw Error('Switch back to the project where you started the timer');const hours=cmd==='stop'?Math.min(24,(Date.now()-timer.start)/3600000).toFixed(3):'1';showForm('Log your time',field('title','Task / work description')+field('hours','Hours','number',hours)+field('rate','Hourly rate (INR)','number','1500')+check('billable','Billable to client'),async b=>{await api('records',{...b,project:project.id,kind:'time'});timer=null});modal.querySelector('[name=hours]').step='.001';modal.querySelector('[name=hours]').min='.001';modal.querySelector('[name=rate]').min='0';return}
if(cmd==='invoice'){showForm('Generate invoice','<p class="muted">All currently unbilled, billable hours in this project will be included and marked invoiced.</p>'+field('title','Invoice description')+field('due','Due date','date'),b=>api('records',{...b,project:project.id,kind:'invoice'}));return}
if(cmd==='viewinvoice'){const r=records.find(r=>r.id===+id);modal.innerHTML=`<article class="invoice">${brand()}<h1 style="margin-top:30px">INVOICE</h1><p>INV-${String(r.id).padStart(4,'0')} · ${esc(r.data.status)}</p><h2>${esc(r.data.title)}</h2><p>Bill to: ${esc(state.orgs.find(o=>o.id===project.org)?.name)}<br>Project: ${esc(project.name)}<br>Due: ${esc(r.data.due)}</p><table><tr><th>Service</th><th>Hours</th><th>Rate</th><th>Amount</th></tr>${r.data.lines.map(l=>`<tr><td>${esc(l.title)}</td><td>${l.hours}</td><td>${money(l.rate)}</td><td>${money(l.hours*l.rate)}</td></tr>`).join('')}</table><h2 style="text-align:right;margin-top:25px">Total: ${money(r.data.amount/100)}</h2><p class="muted">Currency: INR · No tax has been calculated.</p></article><div class="actions">${button('close','Close')}${button('print','Print / Save PDF','primary')}</div>`;modal.showModal();return}
if(cmd==='print'){window.print();return}if(cmd==='pay'){const r=await api('checkout',{id:+id});location.assign(r.url);return}}
document.addEventListener('click',async e=>{const p=e.target.closest('[data-page]'),a=e.target.closest('[data-action]');try{if(p){page=p.dataset.page;render()}if(a)await action(a.dataset.action)}catch(err){toast(err.message)}});
setInterval(async()=>{if(state&&project&&page==='Discussions'&&!modal.open){try{const r=await api('records?project='+project.id);records=r.records;const box=$('#messages');if(box)box.innerHTML=messages()}catch{}}},5000);
try{const status=await api('status');if(status.setup)auth('setup');else if(new URLSearchParams(location.search).has('reset'))auth('reset');else await load()}catch(e){app.innerHTML=empty('Could not connect',esc(e.message))}
